### ISSUE TITLE
Images load slowly on first-time load

### ISSUE THREAD

**Issue by gilwiljam** [fatuma-tahalil/Silver-Robotics-Web-Design#1]
### Description of the issue
Upon loading the site for the first time, all images take 10+ seconds to load fully. For scale, my internet connection is somewhat good (700-800 Mbps download and 50 Mbps upload), but it gets worse the less bandwith you have.

### Steps to reproduce 
If you have never loaded the site, load it and watch the images load. If you have loaded it previously, you can clear your cached images by going to History > Delete Browsing Data > Cached images and files. The banner, the robots page, and all other images take a long time to load. 

### Possible fixes 
The main issue is that high quality images used (9575robot.png, HumberTeamPhoto_9575.JPG and robot_blueAlliance.JPG) are all somewhat uncompressed and take up 5+ MB of storage. Most images on well-designed websites are stored in the jpeg format, are compressed, and are under 1.5 MB of storage, which drastically increases the loading times of the images. 
Will this decrease the quality of the image? Yes, it will, albeit only marginally, and the loading times make up for it. 
 
William.

**Comment by fatuma-tahalil** [comment]
**Changes Made**
Thank you for writing this. In response, I have converted the largest images to JPEG. The issue I am having is that images with transparent backgrounds no longer have transparent backgrounds when converted. So I did not convert those images.

**Comment by gilwiljam** [comment]
There is no need to convert the smaller logo images, for they are already small enough. (Usually sub 500 KB) Good call.
